// ─── Raga Database ───────────────────────────────────────────────────────────
export const RAGAS = [
  {
    id: 'mayamalavagowla',
    melakarta: 'Melakarta 15',
    name: 'Mayamalavagowla',
    time: 'Dawn · Morning',
    notes: ['S', 'R₁', 'G₃', 'M₁', 'P', 'D₁', 'N₃'],
    mood: 'Devotional, Powerful',
    rasa: 'Bhakti (Devotion)',
    arohana: 'S R₁ G₃ M₁ P D₁ N₃ Ṡ',
    avarohana: 'Ṡ N₃ D₁ P M₁ G₃ R₁ S',
    desc: 'The gateway raga — first taught to every Karnatic student. Its wide intervals create a majestic, open sound.',
    compositions: ['Gajavadana Vedha', 'Vatapi Ganapatim'],
    gamakas: ['Kampita on G₃', 'Jaru on N₃→S'],
  },
  {
    id: 'shankarabharanam',
    melakarta: 'Melakarta 29',
    name: 'Shankarabharanam',
    time: 'Midday',
    notes: ['S', 'R₂', 'G₃', 'M₁', 'P', 'D₂', 'N₃'],
    mood: 'Joyful, Majestic',
    rasa: 'Shanta (Serenity)',
    arohana: 'S R₂ G₃ M₁ P D₂ N₃ Ṡ',
    avarohana: 'Ṡ N₃ D₂ P M₁ G₃ R₂ S',
    desc: 'Equivalent to the Western major scale. Universally beloved for its completeness and balance.',
    compositions: ['Endaro Mahanubhavulu', 'Merusamana'],
    gamakas: ['Andolita on G₃', 'Sphurita on R₂'],
  },
  {
    id: 'kharaharapriya',
    melakarta: 'Melakarta 22',
    name: 'Kharaharapriya',
    time: 'Evening',
    notes: ['S', 'R₂', 'G₂', 'M₁', 'P', 'D₂', 'N₂'],
    mood: 'Peaceful, Serene',
    rasa: 'Karuna (Compassion)',
    arohana: 'S R₂ G₂ M₁ P D₂ N₂ Ṡ',
    avarohana: 'Ṡ N₂ D₂ P M₁ G₂ R₂ S',
    desc: 'Rich in melodic possibilities. The natural minor feel gives it a reflective, introspective quality.',
    compositions: ['Balagopala', 'Intakanna'],
    gamakas: ['Nokku on G₂', 'Ravai on D₂'],
  },
  {
    id: 'hanumatodi',
    melakarta: 'Melakarta 8',
    name: 'Hanumatodi',
    time: 'Morning',
    notes: ['S', 'R₁', 'G₂', 'M₁', 'P', 'D₁', 'N₂'],
    mood: 'Melancholic, Deep',
    rasa: 'Karuna & Bhakti',
    arohana: 'S R₁ G₂ M₁ P D₁ N₂ Ṡ',
    avarohana: 'Ṡ N₂ D₁ P M₁ G₂ R₁ S',
    desc: 'Profoundly moving — evoking complete surrender and deep devotion. A raga for serious practice.',
    compositions: ['Nidhi Chala Sukhama', 'Todi Ragam Alapana'],
    gamakas: ['Kampita on G₂', 'Murchana on N₂→S'],
  },
  {
    id: 'harikambhoji',
    melakarta: 'Melakarta 28',
    name: 'Harikambhoji',
    time: 'Evening',
    notes: ['S', 'R₂', 'G₃', 'M₁', 'P', 'D₂', 'N₂'],
    mood: 'Romantic, Sweet',
    rasa: 'Shringar (Love)',
    arohana: 'S R₂ G₃ M₁ P D₂ N₂ Ṡ',
    avarohana: 'Ṡ N₂ D₂ P M₁ G₃ R₂ S',
    desc: 'Parent of many beautiful Janya ragas. Full of warmth and tenderness — ideal for evening concerts.',
    compositions: ['Entaro Mahanubhavulu (Harikambhoji version)', 'Sarasa Sama Dana'],
    gamakas: ['Andolita on N₂', 'Kampita on G₃'],
  },
  {
    id: 'bilahari',
    melakarta: 'Janya of 29',
    name: 'Bilahari',
    time: 'Morning · Noon',
    notes: ['S', 'R₂', 'G₃', 'P', 'D₂'],
    mood: 'Bright, Celebratory',
    rasa: 'Hasya (Joy)',
    arohana: 'S R₂ G₃ P D₂ Ṡ',
    avarohana: 'Ṡ N₃ D₂ P M₁ G₃ R₂ S',
    desc: 'A pentatonic Janya raga with infectious energy. Often chosen for auspicious occasions and concerts.',
    compositions: ['Brochevarevarura', 'Chetashri'],
    gamakas: ['Pratyahata on G₃', 'Jaru on D₂→N₃'],
  },
];

// ─── Karnatic Music Concepts ────────────────────────────────────────────────
export const CONCEPTS = [
  { term: 'Sruti', meaning: 'The tonic pitch — the fundamental note (Sa) from which all other swaras are derived.' },
  { term: 'Swara', meaning: 'A musical note. There are 7 swaras: Sa, Ri, Ga, Ma, Pa, Da, Ni.' },
  { term: 'Gamaka', meaning: 'Melodic ornaments — oscillations, slides, and shakes that give a raga its characteristic flavor.' },
  { term: 'Tala', meaning: 'The rhythmic cycle. Common talas: Adi (8 beats), Rupaka (6 beats), Misra Chapu (7 beats).' },
  { term: 'Arohana', meaning: 'The ascending scale of a raga — the notes used going upward from Sa.' },
  { term: 'Avarohana', meaning: 'The descending scale of a raga — the notes used coming downward to Sa.' },
];
